# Generated by Django 6.0.4 on 2026-05-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.PositiveSmallIntegerField(max_length=7, null=True),
        ),
    ]
